name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go
    
    - name: Install tools
      run: go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: make

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: binaries
        # Directory containing files to upload
        path: dist/
